version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  
  service-a:
    build: ./service-a
    environment:
      - SERVICE_B_URL=http://service-b:8082/weather
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
      - service-b

  service-b:
    build: ./service-b
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "8082:8082"
    depends_on:
      - zipkin
